services:
  Http\Adapter\Guzzle7\Client: ~

  vonage.client.credentials.basic:
    public: false
    class: Nexmo\Client\Credentials\Basic
    arguments:
      - '%botjaeger_vonage.api_key%'
      - '%botjaeger_vonage.api_secret%'

  vonage.client:
    public: true
    class: Nexmo\Client
    arguments:
      - '@vonage.client.credentials.basic'
      - [ ]
      - '@Http\Adapter\Guzzle7\Client'
