services:
    botjaeger_nexmo.client.credentials.basic:
        class: Nexmo\Client\Credentials\Basic
        arguments:
            - '%botjaeger_nexmo.api_key%'
            - '%botjaeger_nexmo.api_secret%'

    botjaeger_nexmo.client:
        public: true
        class: Botjaeger\NexmoBundle\NexmoClient\NexmoClient
        arguments:
            - '@botjaeger_nexmo.client.credentials.basic'